sudo: required
services: docker
language: minimal
env:
  - KUBERNETES_VERSION="v1.16.15" DOCKER_IMAGE_TAG="latest-1.16" MINIKUBE_VERSION="v1.2.0"
  - KUBERNETES_VERSION="v1.17.14" DOCKER_IMAGE_TAG="latest-1.17" MINIKUBE_VERSION="v1.2.0"
  - KUBERNETES_VERSION="v1.18.12" DOCKER_IMAGE_TAG="latest-1.18" MINIKUBE_VERSION="v1.9.2"
  - KUBERNETES_VERSION="v1.19.4" DOCKER_IMAGE_TAG="latest-1.19" MINIKUBE_VERSION="v1.15.1"
script:
  - ./build.sh bsycorp/kind:$DOCKER_IMAGE_TAG bsycorp/kind:$KUBERNETES_VERSION
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
    repo: bsycorp/kind
